# Generated by Django 5.1.4 on 2025-10-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Телефон'),
        ),
    ]
